# fly.toml app configuration file generated for cumpleanios-copiona on 2024-08-27T16:02:08-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'cumpleanios-copiona'
primary_region = 'eze'

[build]

[http_service]
internal_port = 3000
force_https = true
auto_stop_machines = 'stop'
auto_start_machines = true
min_machines_running = 0
processes = ['app']

[[vm]]
size = 'shared-cpu-1x'

[mounts]
source = "cumpleanios_copiona_data"
destination = "/data"

[env]
DATABASE_PATH = "/data/cosos.db"
